[package]
name = "quickey"
version = "0.1.0"
edition = "2024"
include = ["assets", "/src"]

[dependencies]
colog = "1.3.0"
console = "0.15.11"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
